name: Mood-Harmony-Player

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPASS }}" | docker login -u "kryptonguy" --password-stdin
        docker image build --build-arg SPOTIFY_SECRETS=${{ secrets.SPOTIFY_SECRETS }} -t kryptonguy/moodharmonyplayer:latest .
        docker push kryptonguy/moodharmonyplayer